import type { Metadata } from "next";
import "./globals.css";
import SearchOverlay from "@/components/layout/header/search-overlay";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "فروشگاه اینترنتی دیجی کالا",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full antialiased hide-scrollbar`}>
      <body className="min-h-full flex flex-col gap-y-4">
        <SessionProvider>
          {children} <SearchOverlay />
        </SessionProvider>
      </body>
    </html>
  );
}
