import {
  FiX,
  FiSearch,
  FiBell,
  FiMapPin,
  FiChevronLeft,
  FiChevronDown,
  FiChevronRight,
  FiChevronUp,
  FiMenu,
  FiSettings,
  FiPhone,
  FiHelpCircle,
  FiLock,
  FiEdit3,
  FiFileText,
  FiArrowLeft,
  FiHeart,
  FiShoppingBag,
  FiShare2,
  FiArrowRight,
  FiClock,
  FiTrash2,
  FiPlus,
  FiMinus,
} from "react-icons/fi";
import {
  FaRegUser,
  FaRegStar,
  FaUser,
  FaStar,
  FaInstagram,
  FaTwitter,
  FaLinkedin,
  FaTabletAlt,
  FaCaretDown,
} from "react-icons/fa";
import { BsSignpost2 } from "react-icons/bs";
import { TbLogout } from "react-icons/tb";
import { HiOutlineLogin } from "react-icons/hi";
import {
  IoCart,
  IoCartOutline,
  IoWatchOutline,
  IoEyeOutline,
  IoEyeOffOutline,
  IoFlameOutline,
  IoBasketOutline,
  IoPricetagOutline,
  IoBugOutline,
} from "react-icons/io5";
import {
  BiCategory,
  BiSolidCategory,
  BiHome,
  BiSolidHome,
  BiSupport,
} from "react-icons/bi";
import { CiMobile2, CiLaptop, CiHeadphones, CiPercent } from "react-icons/ci";
import { GoDotFill } from "react-icons/go";

export const Icons = {
  Minus: FiMinus,
  Plus: FiPlus,
  Trash: FiTrash2,
  Clock: FiClock,
  RightArrow: FiArrowRight,
  Share: FiShare2,
  Dot: GoDotFill,
  DownFilled: FaCaretDown,
  LeftArrow: FiArrowLeft,
  Heart: FiHeart,
  Bag: FiShoppingBag,
  Edit: FiEdit3,
  Question: FiHelpCircle,
  Lock: FiLock,
  Notes: FiFileText,
  Bug: IoBugOutline,
  Phone: FiPhone,
  Eye: IoEyeOffOutline,
  EyeOutline: IoEyeOutline,
  Setting: FiSettings,
  Mobile: CiMobile2,
  Laptop: CiLaptop,
  Headphones: CiHeadphones,
  Watch: IoWatchOutline,
  Tablet: FaTabletAlt,
  Home: BiSolidHome,
  HomeOutline: BiHome,
  XMark: FiX,
  Search: FiSearch,
  Bell: FiBell,
  Map: FiMapPin,
  Left: FiChevronLeft,
  Down: FiChevronDown,
  Right: FiChevronRight,
  Up: FiChevronUp,
  Cart: IoCart,
  CartOutline: IoCartOutline,
  Category: BiSolidCategory,
  CategoryOutline: BiCategory,
  User: FaUser,
  UserOutline: FaRegUser,
  HamMenu: FiMenu,
  StarOutline: FaRegStar,
  StarFilled: FaStar,
  Instagram: FaInstagram,
  Twitter: FaTwitter,
  Linkedin: FaLinkedin,
  Address: BsSignpost2,
  Signout: TbLogout,
  Signin: HiOutlineLogin,
  Flame: IoFlameOutline,
  Basket: IoBasketOutline,
  PriceTag: IoPricetagOutline,
  Percent: CiPercent,
  Support: BiSupport,
} as const;
