import { Metadata } from "next";
import Nav from "@/components/nav/nav";
import React from "react";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "فروشگاه اینترنتی دیجی کالا",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <SessionProvider>
        {children}
        <Nav />
      </SessionProvider>
    </>
  );
}
